ejecucion:
		g++ ../src/WN_S.cpp -o ../src/WN_S && ../src/WN_S
		g++ ../src/WN_G.cpp -o ../src/WN_G && ../src/WN_G
		g++ ../src/WN_RELATIONS.cpp -o ../src/WN_RELATIONS && ../src/WN_RELATIONS
		pip install -r ../requirements.txt
		py ../src/WN_SOrden.py
		py ../src/WN_GOrden.py
		py ../src/WN_RELATIONSOrden.py
		
traductor:
		g++ ../src/WN_S.cpp -o ../src/WN_S && ../src/WN_S
		g++ ../src/WN_G.cpp -o ../src/WN_G && ../src/WN_G
		g++ ../src/WN_RELATIONS.cpp -o ../src/WN_RELATIONS && ../src/WN_RELATIONS
		pip install -r ../requirements.txt
		py ../src/WN_SOrden.py
		py ../src/WN_GOrden.py
		py ../src/WN_RELATIONSOrden.py
		py src\WN_GIngles.py
		py src\WN_GTraductor.py
		py src\WN_GOrden.py